name: test self hosted runner
run-name: 🚀
on:
  push:
    branches: [main]
jobs:
  task1:
    runs-on: label-1
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: Print Hello World
        run: |
          ls -lah
          pwd
          sh ./printHello.sh
