name: test self hosted runner
run-name: 🚀
on:
  push:
    branches: [main]
jobs:
  task1:
    runs-on: label-1
    outputs:
      origChecksum: ${{steps.calculateChecksum.outputs.origChecksum}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: Print Hello World
        run: |
          ls -lah
          pwd
          sh ./printHello.sh
      - name: upload a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: myArtifacts
          path: myArtifactsFiles
          if-no-files-found: error
          retention-days: 1
      - name: calculate checksum
        id: calculateChecksum
        run: |
          origChecksum=$(sha256sum ./.github/workflows/test_split.yml | awk '{print $1}')
          echo $origChecksum
          echo "origChecksum=$origChecksum" >> $GITHUB_OUTPUT
  task2:
    needs: task1
    uses: ./.github/workflows/test_split.yml
    with:
      originalChecksumOfBinary: ${{origChecksum}}
